# Generated by Django 4.2.30 on 2026-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rooms_inactive_and_cancel_reason_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_key', models.CharField(max_length=96, unique=True)),
                ('phone_normalized', models.CharField(blank=True, default='', max_length=32)),
                ('passport_series', models.CharField(blank=True, default='', max_length=64)),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('doc_full_name', models.CharField(blank=True, default='', max_length=200)),
                ('doc_birth_date', models.CharField(blank=True, default='', max_length=10)),
                ('doc_expiry_date', models.CharField(blank=True, default='', max_length=10)),
                ('doc_citizenship', models.CharField(blank=True, default='', max_length=64)),
                ('doc_number', models.CharField(blank=True, default='', max_length=64)),
                ('doc_type', models.CharField(blank=True, default='', max_length=40)),
                ('doc_extracted_at', models.TextField(blank=True, default='')),
                ('created_at', models.TextField(blank=True, default='')),
                ('updated_at', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Mehmon',
                'verbose_name_plural': 'Mehmonlar',
                'db_table': 'guests',
                'managed': False,
            },
        ),
    ]
